SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE SCHEMA IF NOT EXISTS `DatosTiempo` DEFAULT CHARACTER SET utf8 ;
USE `DatosTiempo` ;
CREATE TABLE IF NOT EXISTS `DatosTiempo`.`Pronostico` (
  `IdDato` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Ciudad` VARCHAR(20) NULL,
  `LunesMin` INT NULL,
  `LunesMax` INT NULL,
  `MartesMax` INT NULL,
  `MartesMin` INT NULL,
  `MiercolesMax` INT NULL,
  `MiercolesMin` INT NULL,
  `JuevesMax` INT NULL,
  `ViernesMin` INT NULL,
  `ViernesMax` INT NULL,
  `SabadoMin` INT NULL,
  `SabadoMax` INT NULL,
  `DomingoMin` INT NULL,
  `DomingoMax` INT NULL,
  PRIMARY KEY (`IdDato`))
ENGINE = InnoDB
COMMENT = '	';

CREATE TABLE IF NOT EXISTS `DatosTiempo`.`DatosReales` (
  `IDDato` INT NOT NULL AUTO_INCREMENT,
  `Fecha y hora` DATETIME NULL,
  `Ciudad` VARCHAR(20) NULL,
  `Temperatura` DECIMAL(1) NULL,
  `Humedad` INT NULL,
  `Presión` INT NULL,
  `viento` INT NULL,
  `visibilidad` INT NULL,
  `estado del clima` VARCHAR(25) NULL,
  PRIMARY KEY (`idDato`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;